### ISSUE TITLE
What Is PSEXEU.exe?

### ISSUE THREAD

**Issue by kwhat** [gpoteau/CommLinkUSB#1]
Hi,

What is the PSEXEU.exe file and is the source code available?  I noticed it was under the MIT license, but I can't find any code anywhere.

Thanks.

**Comment by gpoteau** [comment]
It's the software communicate with the PSX via the hardware, it's a re-make version of the old PSEXE.COM that we used at time with the ACTION REPLAY.
The source code is not available yet.
